name: Branch Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - preview
  release:
    types: [released, prereleased]

env:
  TARGET_BRANCH: ${{ github.ref_name || github.event.release.target_commitish }}

jobs:
  branch_build_setup:
    name: Build Setup
    runs-on: ubuntu-latest
    outputs:
      build_proxy: ${{ steps.changed_files.outputs.proxy_any_changed }}
      build_apiserver: ${{ steps.changed_files.outputs.apiserver_any_changed }}
      build_admin: ${{ steps.changed_files.outputs.admin_any_changed }}
      build_space: ${{ steps.changed_files.outputs.space_any_changed }}
      build_web: ${{ steps.changed_files.outputs.web_any_changed }}

    steps:
      - id: checkout_files
        name: Checkout Files
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v42
        with:
          files_yaml: |
            apiserver:
              - apiserver/**
            proxy:
              - nginx/**
            admin:
              - admin/**
              - packages/**
              - 'package.json'
              - 'yarn.lock'
              - 'tsconfig.json'
              - 'turbo.json'
            space:
              - space/**
              - packages/**
              - 'package.json'
              - 'yarn.lock'
              - 'tsconfig.json'
              - 'turbo.json'
            web:
              - web/**
              - packages/**
              - 'package.json'
              - 'yarn.lock'
              - 'tsconfig.json'
              - 'turbo.json'

  branch_build_push_web:
    if: ${{ needs.branch_build_setup.outputs.build_web == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'release' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [branch_build_setup]
    env:
      FRONTEND_TAG: johannmnn/planeplus-frontend:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and Push Frontend to Docker Hub
        run: |
          docker build -t ${{ env.FRONTEND_TAG }} -f ./web/Dockerfile.web ./web
          docker push ${{ env.FRONTEND_TAG }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

  branch_build_push_admin:
    if: ${{ needs.branch_build_setup.outputs.build_admin == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'release' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [branch_build_setup]
    env:
      ADMIN_TAG: johannmnn/planeplus-admin:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and Push Admin to Docker Hub
        run: |
          docker build -t ${{ env.ADMIN_TAG }} -f ./admin/Dockerfile.admin ./admin
          docker push ${{ env.ADMIN_TAG }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

  branch_build_push_space:
    if: ${{ needs.branch_build_setup.outputs.build_space == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'release' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [branch_build_setup]
    env:
      SPACE_TAG: johannmnn/planeplus-space:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and Push Space to Docker Hub
        run: |
          docker build -t ${{ env.SPACE_TAG }} -f ./space/Dockerfile.space ./space
          docker push ${{ env.SPACE_TAG }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

  branch_build_push_apiserver:
    if: ${{ needs.branch_build_setup.outputs.build_apiserver == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'release' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [branch_build_setup]
    env:
      BACKEND_TAG: johannmnn/planeplus-backend:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and Push Backend to Docker Hub
        run: |
          docker build -t ${{ env.BACKEND_TAG }} -f ./apiserver/Dockerfile.apiserver ./apiserver
          docker push ${{ env.BACKEND_TAG }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

  branch_build_push_proxy:
    if: ${{ needs.branch_build_setup.outputs.build_proxy == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'release' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [branch_build_setup]
    env:
      PROXY_TAG: johannmnn/planeplus-proxy:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and Push Proxy to Docker Hub
        run: |
          docker build -t ${{ env.PROXY_TAG }} -f ./nginx/Dockerfile.nginx ./nginx
          docker push ${{ env.PROXY_TAG }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
